import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from 'next/font/google'

const rubik = Rubik({
  subsets: ['latin'], 
  weight: ["300","400","500","600","700","800","900"], 
  variable: '--font-rubik', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${rubik.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
