import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from 'next/font/google'
import Header from "@/components/common/Header";
import BottomHeader from "@/components/common/BottomHeader";
import Footer from "@/components/common/Footer";
import ReduxProvider from "@/providers/ReduxProvider";
import FloatingButton from "@/components/modules/cart/FloatingButton";
import { ShoppingCart } from "lucide-react";

const rubik = Rubik({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "AutoMart - Your One-Stop Shop for Automotive Needs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${rubik.variable} font-sans bg-[#F8F8F8]`}
      >
        <ReduxProvider>
        <Header />
        <BottomHeader />
        {children}
        {/* Floating cart button */}
        <FloatingButton icon={<ShoppingCart />} label="Cart" />
        <Footer /></ReduxProvider>
      </body>
    </html>
  );
}
